apiVersion: v1 # kubectl get configmap aws-auth -n kube-system -o yaml
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533267120890:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-pZ1zfRqLlXxx
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::533267120890:user/harish
      username: harish
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-04T13:01:57Z"
  name: aws-auth
  namespace: kube-system  
  uid: e6bf4b00-9a6d-4d10-b667-5157d3124063 #don't delete this

